#!/usr/bin/env node
// Build an Artifact-ready single file from the AS-29 style reference.
//
// The style reference (docs/design/style-reference/) is the canonical rendering
// of BRANDING.md — it is generated from the tokens and pinned to the brand doc
// by docs/design/tokens/tokens.test.mjs. This script does NOT redesign it. It
// inlines it, because the Artifact CSP blocks external stylesheets and the
// publish wrapper supplies its own <!doctype>/<html>/<head>/<body>.
//
// Deliberately zero-dependency and string-based: the input is a file we
// control, generated by a suite that fails loudly on drift. If the markers
// below stop matching, that is a real change to the source page and this
// script must fail rather than emit a half-page — see the throw sites.
//
// Usage: node build.mjs <design-dir> <out-file>
//   design-dir  the docs/design directory to read (master or a worktree)
//   out-file    where to write the artifact-ready HTML

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const [, , designDirArg, outFileArg] = process.argv;
if (!designDirArg || !outFileArg) {
  console.error('usage: node build.mjs <design-dir> <out-file>');
  process.exit(2);
}

const designDir = resolve(designDirArg);
const outFile = resolve(outFileArg);

const paths = {
  html: join(designDir, 'style-reference', 'index.html'),
  reference: join(designDir, 'style-reference', 'reference.css'),
  tokens: join(designDir, 'tokens', 'tokens.css'),
};

for (const [name, p] of Object.entries(paths)) {
  if (!existsSync(p)) {
    throw new Error(`missing ${name}: ${p}\nIs AS-29 merged, or should you point at .worktrees/AS-29/docs/design?`);
  }
}

const html = readFileSync(paths.html, 'utf8');
const referenceCss = readFileSync(paths.reference, 'utf8');
const tokensCss = readFileSync(paths.tokens, 'utf8');

// A stylesheet that arrived empty would publish a page with no styling at all
// and no error — the vacuous-pass failure class this repo has hit five times
// (AS-17, AS-26, AS-29 cycles 1 and 2). Refuse instead.
const FLOOR = 2000;
for (const [name, css] of [['tokens.css', tokensCss], ['reference.css', referenceCss]]) {
  if (css.trim().length < FLOOR) {
    throw new Error(`${name} is ${css.trim().length} bytes, below the ${FLOOR}-byte floor — refusing to publish an unstyled page`);
  }
}

const titleMatch = /<title>([\s\S]*?)<\/title>/i.exec(html);
if (!titleMatch) throw new Error('no <title> found in index.html');

const bodyMatch = /<body[^>]*>([\s\S]*)<\/body>/i.exec(html);
if (!bodyMatch) throw new Error('no <body>…</body> found in index.html');
const body = bodyMatch[1];

if (body.trim().length < 10000) {
  throw new Error(`extracted body is only ${body.trim().length} bytes — the markers probably drifted; refusing to publish a truncated page`);
}

// The publish wrapper injects <!doctype>, <html>, <head> and <body>, so the
// file is page CONTENT: a <title>, a <style>, then the markup. Any <link> in
// the source is dropped — its stylesheet is inlined above it instead.
const out = `<title>The American Software Company</title>
<style>
/* ------------------------------------------------------------------ *
 * Inlined from docs/design/tokens/tokens.css — generated, do not edit
 * here. Edit BRANDING.md, then re-run the brand-artifact skill.
 * ------------------------------------------------------------------ */
${tokensCss}
/* ------------------------------------------------------------------ *
 * Inlined from docs/design/style-reference/reference.css
 * ------------------------------------------------------------------ */
${referenceCss}
</style>
${body}
`;

writeFileSync(outFile, out);

const kb = (n) => `${(n / 1024).toFixed(1)}kB`;
console.log(`wrote ${outFile}`);
console.log(`  source title : ${titleMatch[1].trim()}`);
console.log(`  tokens.css   : ${kb(tokensCss.length)}`);
console.log(`  reference.css: ${kb(referenceCss.length)}`);
console.log(`  body         : ${kb(body.length)}`);
console.log(`  total        : ${kb(out.length)}`);
