// Priya, AS-56 review: host-side falsifiers. Each mutation: backup, restore on
// exit (try/finally + process 'exit' hook), mutate, ASSERT APPLIED AT THE
// INTENDED SITE, run, restore, prove tree clean with git diff --exit-code.
import { readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
const W = '/Users/forrest/Code/american-software-company/.worktrees/AS-56';
const OUT = '/Users/forrest/Code/american-software-company/scratchpad/agent-qa-priya/AS-56';
const TOK = `${W}/docs/design/tokens/tokens.css`;
const BR = `${W}/BRANDING.md`;
const CHAT = `${W}/apps/chat/public/tokens.css`;
const JSONP = `${W}/docs/design/tokens/tokens.json`;
const files = { [TOK]: `${OUT}/tokens.css.bak`, [BR]: `${OUT}/BRANDING.md.bak`, [CHAT]: `${OUT}/chat-tokens.css.bak`, [JSONP]: `${OUT}/tokens.json.bak` };
for (const [src, bak] of Object.entries(files)) copyFileSync(src, bak);
const restore = () => { for (const [src, bak] of Object.entries(files)) copyFileSync(bak, src); };
process.on('exit', restore);

const sh = (bin, args) => spawnSync(bin, args, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
const redLines = (out) => out.split('\n').filter((l) => /^(not ok|✖)|^ℹ (tests|pass|fail)|AssertionError|Expected values|^\s*[+-] \d|message:/.test(l)).slice(0, 40).join('\n');
const runTokens = () => { const r = sh('node', ['--test', `${W}/docs/design/tokens/tokens.test.mjs`]); return redLines(r.stdout + r.stderr); };
const runChat = () => { const r = sh('node', ['--test', `${W}/apps/chat/test/tokens-parity.test.js`]); return redLines(r.stdout + r.stderr); };
const treeClean = (label) => { const r = sh('git', ['-C', W, 'diff', '--exit-code', '--stat']); console.log(`${label}: tree ${r.status === 0 ? 'CLEAN' : 'DIRTY\n' + r.stdout}`); };
const mutate = (path, pattern, replacement, expectCount, label) => {
  let s = readFileSync(path, 'utf8');
  const count = s.split(pattern).length - 1;
  if (count !== expectCount) { console.log(`${label}: mutation NOT applied as intended (${count} sites, expected ${expectCount}) — abort`); process.exit(9); }
  s = s.split(pattern).join(replacement);
  writeFileSync(path, s);
  const after = readFileSync(path, 'utf8').split(replacement).length - 1;
  console.log(`${label}: applied at ${count} site(s), verified ${after} replacement(s) on disk`);
};

console.log('=========== M1 (AC-1 falsifier): dark danger-solid alias back to danger-500 in BOTH dark blocks ===========');
mutate(TOK, '--color-danger-solid: var(--color-danger-400);', '--color-danger-solid: var(--color-danger-500);', 2, 'M1');
console.log(readFileSync(TOK, 'utf8').split('\n').map((l, i) => [i + 1, l]).filter(([, l]) => l.includes('danger-solid: var')).map(([n, l]) => `  L${n}: ${l.trim()}`).join('\n'));
console.log(runTokens());
restore(); treeClean('M1');

console.log('\n=========== M2 (AC-2 falsifier): BRANDING.md §3.4 new bg-surface row 3.17 -> 3.99 ===========');
mutate(BR, '| `danger-solid` boundary vs `bg-surface` (non-text) | 3.17:1 | 3:1 | PASS |', '| `danger-solid` boundary vs `bg-surface` (non-text) | 3.99:1 | 3:1 | PASS |', 1, 'M2');
console.log(runTokens());
restore(); treeClean('M2');

console.log('\n=========== M2b (AC-2 variant): the labelled FAIL row 2.51 -> 2.99 (does a FAIL row get recomputed at all?) ===========');
mutate(BR, '| `danger-solid` boundary vs `bg-surface-sunken` (non-text) | 2.51:1 | 3:1 | FAIL', '| `danger-solid` boundary vs `bg-surface-sunken` (non-text) | 2.99:1 | 3:1 | FAIL', 1, 'M2b');
console.log(runTokens());
restore(); treeClean('M2b');

console.log('\n=========== M3 (extra): one byte in apps/chat/public/tokens.css (the new -400 hex) — chat parity guard ===========');
mutate(CHAT, '--color-danger-400: #D62937;', '--color-danger-400: #D62938;', 1, 'M3');
console.log(runChat());
restore(); treeClean('M3');

console.log('\n=========== M4 (extra): same byte in docs tokens.css only — chat sha pin ===========');
mutate(TOK, '--color-danger-400: #D62937;', '--color-danger-400: #D62938;', 1, 'M4');
console.log(runChat());
restore(); treeClean('M4');

console.log('\n=========== M5 (extra): remove the danger-400 primitive line from docs tokens.css only — token suite count guards ===========');
mutate(TOK, '  --color-danger-400: #D62937; /* AS-56: L=50 step generated by BRANDING.md §11; dark danger-solid moved here from -500 to clear 3:1 on bg-surface */\n', '', 1, 'M5');
console.log(runTokens());
restore(); treeClean('M5');

console.log('\n=========== M6 (extra): style-reference callout 11 -> 12 (is the callout count guarded?) ===========');
const HTML = `${W}/docs/design/style-reference/index.html`;
copyFileSync(HTML, `${OUT}/index.html.bak`); files[HTML] = `${OUT}/index.html.bak`;
mutate(HTML, '<strong>11 combinations fail', '<strong>12 combinations fail', 1, 'M6');
console.log(runTokens() || '(no red lines — SURVIVOR)');
restore(); treeClean('M6');
