import { readFileSync, writeFileSync } from 'node:fs';
const p = '/Users/forrest/Code/american-software-company/scratchpad/agent-qa-priya/AS-125/review-comment.md';
let s = readFileSync(p, 'utf8');
const sweep = `AC-1 PASS — H7/H8/H9 present under the §2.7 names (verified in the diff and by the file's 10 cases); H4's control is \`.t span\`; host on $W = 615 / 613 / 0 / 2 (= the plan's 612 + 3; master is now 613 after AS-109, so a post-merge master run should read 616); file alone 10/10.
AC-2 PASS — A1 red exactly {T1}: \`won by #roster-list li.roster-row div (spec 1,1,2, order 210)\`; A2 exactly {T1}: \`won by #roster-list * (spec 1,0,0, order 210)\`. Each message also carries cardinality: \`211 rules parsed, 4 target .roster-title\`.
AC-3 PASS — A3 exactly {T1}: \`won by [class~="roster-title"] (spec 0,1,0, order 210)\`; A3b exactly {T1}: \`won by [class~=roster-title] (spec 0,1,0, order 210)\`; A4 exactly {T1}: \`won by .roster-title (spec 0,1,0, order 210)\` with the applied check \`.roster\\-title {\` 0→1 and \`.roster-title {\` 2→2.
AC-4 PASS — B1 exactly {T1}, thrown \`cannot score unknown at-rule (neither flattened nor ignored): @scope (#roster-list)\`; B2 exactly {T1}, thrown \`cannot score: statement at-rule or stray ';' glued into a prelude: @import url("x.css"); .roster-title\`; B3 exactly {T1}, thrown \`… unknown at-rule …: @layer x\`.
AC-5 PASS — C1 exactly {T1}, thrown \`unbalanced braces: depth 1 at end of input (unclosed block opened by: .roster-status::after)\`; C2 exactly {T1}, thrown \`unbalanced braces: stray '}' at offset 16370\` (\`}\` count 191→192; the offset is into the comment-stripped source — cosmetic); C3 exactly {T1}, thrown \`trailing content without a block: @import url("x.css");\`.
AC-6 PASS — N1 (\`#roster-list span\`) and N2 (\`#roster-list div.other\`) both GREEN at 615 / 613 / 0 / 2, observed.
AC-7 PASS — R1 exactly {T1} \`won by .roster-title (spec 0,1,0, order 210)\` (2→3); R2 exactly {T1} \`won by #roster-list .roster-title (spec 1,1,0, order 50)\` (inserted at index 5825 < base rule 6244); R3 exactly {T1} \`.roster-title all: effective value is unset — … the contract allows undeclared\`; R4 exactly {T1}, thrown \`cannot score nested style rule (native CSS nesting) under: #roster-list\` from walk() L178 — the nesting throw, not the at-rule or ';' throw, so the check order holds.
AC-8 PASS — G1 (\`lastCompound(\` in targets() 1→0) red exactly {H9} \`expected [class~="t"] to target .t\`, T1 GREEN (615/612/1); F7/F8/F9 red exactly {H7}/{H8}/{H9}, 10/9/1 in the file alone each, and exactly one red in the whole suite each (F8's whole-suite companion needed a second attempt — see the tally).
AC-9 PASS — \`git diff --stat master...branch\` = 1 file, apps/chat/test/roster-truncation.test.js; \`--exit-code\` on public/, server.js, lib/, api.test.js, fixtures, package.json, .lattice/, top-level files → 0.
AC-10 PASS — compose receipt \`Image asc-review-as125-test Built\`, 615 / 607 / 0 / 8, run exit 0, down exit 0, leak check clean; skip delta 6 as predicted.
AC-11 PASS — scratch worktree /tmp/AS-125-mutant removed (\`git worktree list\` shows master, AS-124, AS-125, AS-126 only); $W porcelain empty on feat/AS-125-cascade-guard-routes; post-restore host green at 615 after every mutant (22 restore runs); \`compose-run.mjs --check\` → 3 production networks, no leftovers.
Floor check: 11 of 11 pass. Findings outside this list: 2 (N1, N2 above) + 1 observation (the AS-84 flake in the tally).`;
const tally = `21 planned runs, 21 observed with EXACTLY the predicted red set (0 survivors, 0 wider, 0 narrower), all on a detached scratch worktree (/tmp/AS-125-mutant at 7690a5a), each with an applied-at-site assertion (occurrence count over the stylesheet, or over the named function / test body), whole host suite per run, restore by \`git checkout -- apps/chat\`, porcelain proven empty, post-restore green at 615/613/0/2 before the next mutant. Driver + log: scratchpad/agent-qa-priya/AS-125/mutants.mjs, mutants.log, mutants-C2_F8_F9.log, raw-<id>.log.
Two runs needed a second attempt and both were MY driver's fault, not the branch's: C2's apply-check compared the \`}\` count against 0 instead of the pre-mutation 191 (the driver restored without running the suite; re-run 191→192, red exactly {T1}); F9's site check counted \`'#r li.row div'\` twice because H9's \`assert.equal(won.selector, '#r li.row div')\` line matches too (narrowed to the comma-terminated array entry; re-run red exactly {H9}). Marcus's comment (read after my findings were written) records hitting the identical F9 trap — the discipline caught a loose check both times.
One wider-than-predicted companion run, run down: F8's first whole-suite companion returned 2 red — {H8} plus \`AS-84 entry point: SIGTERM mid-build terminates the compose child, leaves no lock, records the abort, exits 0\` (a watcher test in a file this branch does not touch). It ran while two of my own pacing suites were executing concurrently (three suites on the box); the re-run with no concurrent suites returned exactly {H8}, and 23 independent host runs of $W during the battery all read 615/613/0/2. Observation, not a finding on this task: a timing-sensitive watcher case under load, seen once (the known AS-83-condition flake is mode.test.js, a different case). Seen again, it becomes a task under the recurring-observation rule.
Beyond the battery: the 9 routes driven directly through cascade()/parseRules() on a verbatim copy of the branch helper (A1–A4 red with the predicted winner and specificity; B1–B3 and C1 thrown with the predicted messages) and 65 M6/edge probes (probes.out, probes2 output).`;
const cleanup = 'Scratch worktree removed; $W status clean (no inline-fix commit — none was needed); `compose-run.mjs --check` shows no asc-*as125* leftover; nothing under $M touched except scratchpad/agent-qa-priya/AS-125/. No `lattice status`, no master commit, no merge — those are Owen\'s.';
const verdict = `PASS. The plan was sound and the implementation matches it line for line; every acceptance criterion is satisfied by an observed red (or an observed green for the narrowness controls), and the probing past the list found two silent routes (N1 comma-in-attribute-value, N2 namespace prefix) that are outside this task's eight routes and inside §1.4's recorded exclusions — the orchestrator files them as follow-ups, and the record should carry my correction that the comma split is NOT conservative in every ordering. Merge. For the file: this review ran on Opus under the Fable-limit fallback.`;
s = s.replace('MUTANTS_PLACEHOLDER', sweep).replace('TALLY_PLACEHOLDER', tally).replace('CLEANUP_PLACEHOLDER', cleanup).replace('VERDICT_PLACEHOLDER', verdict);
writeFileSync(p, s);
console.log('length', s.length, 'placeholders left:', /PLACEHOLDER/.test(s));
